AppBundle\Domain\Model\Trading\PrincipalBonds:
    type: entity
    repositoryClass: AppBundle\Domain\Repository\BondsRepository

    table: bonds
    id:
        id:
            type: integer
            generator: { strategy: "AUTO" }

    uniqueConstraints:
        symbol:
            columns: symbol

    fields:
        symbol:
            type: string
            length: 50
        faceValue:
            column: face_value
            type: decimal
            scale: 4
        maturityDate:
            column: maturity_date
            type: date

    oneToOne:
        interest:
            targetEntity: AppBundle\Domain\Model\Trading\Interest
            cascade: [all]
            joinColumn:
                name: interest
                referencedColumnName: id









