AppBundle\Domain\Model\Trading\PrincipalBonds:
    type: entity
    repositoryClass: AppBundle\Domain\Repository\BondsRepository

    table: bonds
    id:
        id:
            type: integer
            generator: { strategy: "AUTO" }

    indexes:
        symbol:
            columns: symbol

    fields:
        symbol:
            type: string
            length: 50
        faceValue:
            column: face_value
            type: decimal
            scale: 4
        maturityDate:
            column: maturity_date
            type: date
        interest:
            column: interest
            type: decimal
            scale: 4
        interestType:
            column: interest_type
            columnDefinition: enum("fixed", "variable")
        interestInterval:
            column: interest_interval
            type: type_date_interval







